"""Regenerate the README's performance section from recorded benchmark runs.

Owns: turning `docs/benchmarks/*.json` into the markdown table the README shows.
Does NOT own: measuring anything. The application writes those files with
`--metrics-out`.

This exists so a published number is never a retyped one. Every figure in the
README's performance section is read from a file that also carries the hardware
and the full configuration that produced it, and the section is rewritten in
place between its markers:

    python tools/performance_table.py          # rewrite README.md
    python tools/performance_table.py --check   # fail if it is out of date

The --check mode is what makes the guarantee real rather than aspirational: an
edited number and a stale file are the same failure, and both are caught.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
BENCHMARKS = Path(__file__).resolve().parents[1] / "docs" / "benchmarks"
README = REPO_ROOT / "README.md"

BEGIN = "<!-- generated by biomech/tools/performance_table.py - do not edit by hand -->"
END = "<!-- end generated -->"

# Display order and prose label per run. Keyed by the `label` the run was given,
# so a benchmark file that is added without being described here is reported
# rather than silently dropped into an arbitrary position.
RUNS: dict[str, str] = {
    "camera-full-ui": "**Live camera, full UI** (30 s)",
    "long-full-ui": "Video replay, full UI (72 s)",
    "long-headless": "Video replay, headless (72 s)",
    "squat-full-ui-8-cpu-hogs": "Under heavy CPU contention",
}


def load_runs() -> dict[str, dict]:
    """Every recorded benchmark, keyed by its label."""
    if not BENCHMARKS.is_dir():
        raise SystemExit(f"No benchmark directory at {BENCHMARKS}")
    runs = {}
    for path in sorted(BENCHMARKS.glob("*.json")):
        report = json.loads(path.read_text(encoding="utf-8"))
        runs[report["label"]] = report
    if not runs:
        raise SystemExit(f"No benchmark files in {BENCHMARKS}")
    return runs


def _hardware_line(report: dict) -> str:
    hw = report["hardware"]
    return (
        f"Measured on {hw['platform']}, {hw['cpu_count']} logical cores, "
        f"Python {hw['python']}."
    )


def render(runs: dict[str, dict]) -> str:
    """The markdown block, built from the files rather than from memory."""
    lines = [
        BEGIN,
        "",
        "| Run | Displayed FPS | Inference p50 | Biomech p50 | Render p50 "
        "| Latency p50 / p95 | Drops |",
        "|---|---|---|---|---|---|---|",
    ]
    kinds: set[str] = set()
    for label, title in RUNS.items():
        report = runs.get(label)
        if report is None:
            continue
        m = report["metrics"]
        # Replay from a landmark recording measures processing time, not latency
        # from capture. Both are useful; putting them in one column unlabelled
        # would be the exact conflation this project measures against.
        kinds.add(report["latency_kind"])
        if report["latency_kind"] != "end_to_end":
            title += f" [{report['latency_kind']}]"
        render_ms = m["render_p50_ms"]
        rendered = "-" if render_ms != render_ms else f"{render_ms:.1f} ms"  # NaN: headless
        lines.append(
            f"| {title} | **{m['displayed_fps']:.1f}** | {m['inference_p50_ms']:.1f} ms "
            f"| {m['biomech_p50_ms']:.2f} ms | {rendered} "
            f"| {m['end_to_end_p50_ms']:.1f} / {m['end_to_end_p95_ms']:.1f} ms "
            f"| {m['source_drops']:.0f} |"
        )

    unknown = sorted(set(runs) - set(RUNS))
    if unknown:
        lines += ["", f"<!-- not shown: {', '.join(unknown)} -->"]

    reference = runs.get("camera-full-ui") or next(iter(runs.values()))
    lines += [""]
    if kinds - {"end_to_end"}:
        lines += [
            "Latency is measured from capture unless a row says otherwise; a row marked "
            "`[processing]` replays recorded landmarks and has no capture instant.",
            "",
        ]
    lines += [_hardware_line(reference), "", END]
    return "\n".join(lines)


def splice(readme: str, block: str) -> str:
    """Replace the generated region, leaving everything around it untouched."""
    if BEGIN not in readme or END not in readme:
        raise SystemExit(
            f"{README.name} has no generated region. Add the markers:\n{BEGIN}\n{END}"
        )
    head = readme.split(BEGIN)[0]
    tail = readme.split(END, 1)[1]
    return head + block + tail


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the README does not match the recorded runs",
    )
    args = parser.parse_args(argv)

    updated = splice(README.read_text(encoding="utf-8"), render(load_runs()))
    current = README.read_text(encoding="utf-8")

    if args.check:
        if updated != current:
            print(f"{README.name} performance section is out of date. "
                  f"Run: python biomech/tools/performance_table.py")
            return 1
        print(f"{README.name} performance section matches docs/benchmarks/.")
        return 0

    if updated == current:
        print(f"{README.name} already up to date.")
        return 0
    README.write_text(updated, encoding="utf-8")
    print(f"Rewrote the performance section of {README.name}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
